path: /content/dataset # dataset root dir
train: images/train # train images (relative to 'path')
val: images/val # val images (relative to 'path')

# Classes
names:
  0: can
  1: petbottle
  2: plastic
  3: glass
  4: raw-trash
  5: paper-carton
  6: nonburnable